-- 서울시 구별 유입인구(Mapbox), 서울시 구별 유입 인구(Bar), 요일별 유출 인구(Line), 매 시간별 유출인구(Line) 을 생성하는 데 사용되는 테이블 생성 쿼리문
CREATE TABLE DASHBOARD_PROJECT.ANALYTICS.map_info_test AS  
SELECT
    fp.*,
    d.LON AS DEPARTURE_DISTRICT_LON,
    d.LAT AS DEPARTURE_DISTRICT_LAT,
    d.LON AS ARRIVAL_DISTRICT_LON,
    d.LAT AS ARRIVAL_DISTRICT_LAT
FROM
    DASHBOARD_PROJECT.ANALYTICS.DAY_OF_WEEK_FLOATING_POPULATION2 fp
JOIN
    DASHBOARD_PROJECT.RAW_DATA.DISTRICT d ON fp.DISTRICT_NAME = d.DISTRICT_NAME
LEFT JOIN
    DASHBOARD_PROJECT.ANALYTICS.DAY_OF_WEEK_FLOATING_POPULATION2 a ON fp.DISTRICT_NAME = a.DISTRICT_NAME;

-- 최종 테이블 형태
TABLE DASHBOARD_PROJECT.ANALYTICS.MAP_INFO_TEST (
	MOVING_MONTH VARCHAR(16777216),
	MOVING_DAY_OF_WEEK VARCHAR(16777216),
	ARRIVAL_TIME NUMBER(38,0),
	DEPARTURE_DISTRICT_CODE VARCHAR(16777216),
	DEPARTURE_DISTRICT_NAME VARCHAR(16777216),
	ARRIVAL_DISTRICT_CODE VARCHAR(16777216),
	DISTRICT_NAME VARCHAR(16777216),
	GENDER VARCHAR(1),
	AGE NUMBER(38,0),
	MOVING_TYPE VARCHAR(16777216),
	AVERAGE_MOVING_TIME_MINUTE FLOAT,
	MOVING_POPULATION_TOTAL NUMBER(38,0),
	NUMBER NUMBER(38,0),
	DEPARTURE_DISTRICT_LON FLOAT,
	DEPARTURE_DISTRICT_LAT FLOAT,
	ARRIVAL_DISTRICT_LON FLOAT,
	ARRIVAL_DISTRICT_LAT FLOAT
);
